// demos/react/counter/src/index.tsx
import { ActorSystem } from '@d-buckner/ensemble-core';
import { EnsembleProvider } from '@d-buckner/ensemble-react';
import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import { CounterActor } from './actors/CounterActor';
import { App } from './App';
import { CounterToken } from './tokens';
import ensembleConfig from '../ensemble.json';


async function main() {
  // Load thread configuration from ensemble.json
  const system = new ActorSystem(ensembleConfig);

  system.register({
    token: CounterToken,
    actor: CounterActor
  });

  await system.start();

  const root = createRoot(document.getElementById('root')!);
  root.render(
    <StrictMode>
      <EnsembleProvider system={system}>
        <App />
      </EnsembleProvider>
    </StrictMode>
  );

  (window as any).system = system;
}

main().catch(console.error);

// demos/solidjs/metrics-dashboard/src/index.tsx
import { ActorSystem } from '@d-buckner/ensemble-core';
import { EnsembleProvider } from '@d-buckner/ensemble-solidjs';
import { render } from 'solid-js/web';
import { AnomalyDetectionActor } from './actors/AnomalyDetectionActor';
import { DashboardActor } from './actors/DashboardActor';
import { MetricGeneratorActor } from './actors/MetricGeneratorActor';
import { StatisticsActor } from './actors/StatisticsActor';
import { App } from './App';
import { GeneratorToken, StatisticsToken, AnomalyDetectionToken, DashboardToken } from './tokens';
import ensembleConfig from '../ensemble.json';


async function main() {
  // Load thread configuration from ensemble.json
  const system = new ActorSystem(ensembleConfig);

  // Register actors in dependency order
  system.register({
    token: GeneratorToken,
    actor: MetricGeneratorActor
  });

  system.register({
    token: StatisticsToken,
    actor: StatisticsActor,
    dependencies: {
      MetricGeneratorActor: GeneratorToken
    }
  });

  system.register({
    token: AnomalyDetectionToken,
    actor: AnomalyDetectionActor,
    dependencies: {
      StatisticsActor: StatisticsToken
    }
  });

  system.register({
    token: DashboardToken,
    actor: DashboardActor,
    dependencies: {
      StatisticsActor: StatisticsToken,
      AnomalyDetectionActor: AnomalyDetectionToken
    }
  });

  await system.start();

  const root = document.getElementById('app')!;
  render(
    () => (
      <EnsembleProvider system={system}>
        <App />
      </EnsembleProvider>
    ),
    root
  );

  (window as any).system = system;
}

main().catch(console.error);
